spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stSystem?useSSL=false&serverTimezone=UTC
    username: root
    password: admin2020
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create